---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: docker4win/backend:b31f1d18ad3293878ddf843ecc1796a439085b70
        name: backend
        ports:
        - containerPort: 5000
          name: flask
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: flask
  selector:
    app: backend
